language: cpp

matrix:
  include:
    - name: "linux_x64"
      os: linux
      sudo: required
      env: 
        - DOCKER_IMAGE=pmeira/manylinux_wheel_cmake_fpc
        - KLUSOLVE_OS=linux
        - KLUSOLVE_ARCH=x64
      services:
        - docker
      install:
        - docker pull $DOCKER_IMAGE
      script: 
        - wget https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/v5.6.0.tar.gz -O suitesparse.tar.gz -q
        - tar zxf suitesparse.tar.gz
        - mv SuiteSparse-5.6.0 SuiteSparse
        - mv SuiteSparse ..
        - wget http://bitbucket.org/eigen/eigen/get/3.3.7.tar.gz -O eigen3.tar.gz -q
        - tar zxf eigen3.tar.gz
        - mv eigen-eigen-323c052e1731 ..
        - docker run --rm -v `pwd`/..:/io -e TRAVIS_TAG="${TRAVIS_TAG}" $DOCKER_IMAGE bash /io/klusolve/ci/build_linux_x64.sh
        - ls -lR lib
        - bash ci/pack_travis.sh
        
    - name: "linux_x86"
      os: linux
      sudo: required
      env: 
        - DOCKER_IMAGE=pmeira/manylinux_wheel_cmake_fpc_i686
        - KLUSOLVE_OS=linux
        - KLUSOLVE_ARCH=x86
      services:
        - docker
      install:
        - docker pull $DOCKER_IMAGE
      script: 
        - wget https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/v5.6.0.tar.gz -O suitesparse.tar.gz -q
        - tar zxf suitesparse.tar.gz
        - mv SuiteSparse-5.6.0 SuiteSparse
        - mv SuiteSparse ..
        - wget http://bitbucket.org/eigen/eigen/get/3.3.7.tar.gz -O eigen3.tar.gz -q
        - tar zxf eigen3.tar.gz
        - mv eigen-eigen-323c052e1731 ..
        - docker run --rm -v `pwd`/..:/io -e TRAVIS_TAG="${TRAVIS_TAG}" $DOCKER_IMAGE linux32 bash /io/klusolve/ci/build_linux_x86.sh
        - ls -lR lib
        - bash ci/pack_travis.sh
        
    - name: "osx_x64"
      os: osx
      env: 
        - KLUSOLVE_OS=darwin
        - KLUSOLVE_ARCH=x64
      install: true
      script: 
        - mkdir build
        - cd build
        - cmake -DUSE_SYSTEM_SUITESPARSE=OFF -DUSE_SYSTEM_EIGEN3=OFF ..
        - cmake --build . --config Release
        - cd ..
        - file lib/darwin_x64/libklusolvex.dylib
        - ls -lR lib
        - bash ci/pack_travis.sh

deploy:
    provider: releases
    api_key:
        secure: Zaxa30lrRXT2MsFWoiu8RrXiHAdiR3k/51IGB0uPEPFNtjTSS0gh//YRtbi9zQIuWKCO3Ogejksi/mczk8JFMeBKLn5AkWKL+/fvXJpwjD/vrfVu20aW0MRhNGwK8XK5HF1hFldoAxqzWJewjVwZjaKmOXo2dJJcyC1/fOxjiz348aVS/fDBYpufuAs6frHvx4ZcCK9qfNQzI8SuFoUmLCmrzzEXi/AoF/KIrsuLLQWpFKZvecUx435if+WY7Cs0xYvMA+SyPT7fbt4Fjmt4U1dsZeLQHGDUIF9gSiOH6lNCKe0mexls4nHi+6QFAczIxS8JxsHA+k6x5pV9hvvED3EO6Xh4uAeWI+JsmrdMvvvP02IfBeGInoTkGp8t3TYfwzun3W3W5AofT5xdtvvZDWGyi5ekbkqt95+JWtciB2giSlsmkJxgv3mcILmMTGauKtzz3/vBSX+HllCIUNwGXq1PhW57u4qS0gyob+xfM9kM0aGY5sjT3kVEXZoiZbdbkQFBZT8xaJllRjUZZQ/I+XSvcbAAvrrAqk6Yp6RZaLytbur6mRFJD1s4cc8YfcBtmBA4umzsrXov8xID7st5/C7dHIUO+Mxw813EedykRZXEB43pNNWcQZZjSY8GJSowdBULR1EPZiSADANK4AVz7l/LNClrDwzKRz0OcujjFJw=
    file_glob: true
    file: release/*
    draft: true
    skip_cleanup: true
    on:
        repo: dss-extensions/klusolve
        tags: true
